### ISSUE TITLE
8-bit translation raises error CUBLAS_STATUS_NOT_SUPPORTED on Ampere GPU

### ISSUE THREAD

**Issue by beichao1314** [OpenNMT/CTranslate2#414]
Hi,
I install ctranslate2 by pip. Run: translator.translate_batch(), I get error: RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED
Then, I compile with CUDA from source, get error: 
```
[  1%] Building NVCC (Device) object CMakeFiles/ctranslate2.dir/src/ops/ctranslate2_generated_quantize_gpu.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_86'
CMake Error at ctranslate2_generated_quantize_gpu.cu.o.Release.cmake:220 (message):
  Error generating
  /host/mercube/running/CTranslate2/build/CMakeFiles/ctranslate2.dir/src/ops/./ctranslate2_generated_quantize_gpu.cu.o


make[2]: *** [CMakeFiles/ctranslate2.dir/build.make:121: CMakeFiles/ctranslate2.dir/src/ops/ctranslate2_generated_quantize_gpu.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/ctranslate2.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
The GPU is RTX3060, the version of CUDA is 11.0. I've run pytorch model and it's worked.
Does CTranslate2 support RTX30 series?

**Comment by guillaumekln** [comment]
> I install ctranslate2 by pip. Run: translator.translate_batch(), I get error: RuntimeError: cuBLAS failed with status CUBLAS_STATUS_NOT_SUPPORTED

This is not expected. Can you share the code that produced this error?

> Then, I compile with CUDA from source, get error:

Compiling for compute capability 8.6 requires CUDA 11.1, but you can select compute capability 8.0 which should be compatible with both CUDA 11.0 and the RTX 3060:

```
cmake -DWITH_CUDA=ON -DCUDA_ARCH_LIST="8.0" ..
```

**Comment by guillaumekln** [comment]
I'm closing this issue for inactivity. If you can provide more information on how you got the error `CUBLAS_STATUS_NOT_SUPPORTED`, please reopen this issue.

**Comment by alrudak** [comment]
Got the same problem on A100 GPU


Before CUBLAS_NOT_SUPPORTED we got "Out of memory” error.

We run 2 models, each of 300mb. But in Nvidia-SMI I saw that only 1GB of 40GB is used and then get “out of memory"

To convert models to CTRanslate I used that command (to create 8 bit models)

ct2-opennmt-tf-converter --model_path INPUT_ONMT_MODEL_DIR --model_spec TransformerBig --output_dir OUTPUT_DIR --quantization int8

May be it’s because of “fabric manager”, that need to run with A100 GPU ?
https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-460-32-03/index.html

The Translator object creates like:
model = ctranslate2.Translator(path, device=DEVICE)

The package version:
opennmt/ctranslate2:latest-ubuntu18-cuda11.0

**Comment by guillaumekln** [comment]
Thanks for the info.

Do you get the same error if you use the `float` or `float16` compute types?

```python
model = ctranslate2.Translator(path, device=DEVICE, compute_type="float")
```

**Comment by guillaumekln** [comment]
So I don't have access to an Ampere GPU at the moment, but I have a possible fix after reading the cuBLAS documentation. @alrudak Could you try this Docker image and see if you still get the error: `opennmt/ctranslate2:dev-ubuntu18-cuda11.0`

**Comment by beichao1314** [comment]
Sorry to reply late cause the machine.
I compile from source with CUDA11.1 and it worked.
Thanks for your help!

**Comment by alrudak** [comment]
I can confirm that 8-bit raises this error.

**Comment by guillaumekln** [comment]
Yes, as far as I know this is an issue with int8 only. You could set `compute_type="float16"` as a workaround.

I think we need to update the CUDA version used in the Python package to properly support Ampere GPUs.

**Comment by alrudak** [comment]
> Yes, as far as I know this is an issue with int8 only. You could set `compute_type="float16"` as a workaround.
> 
float16 also don't work on A100

**Comment by guillaumekln** [comment]
Ok, thanks for the feedback. I tested `float16` on a P4 AWS instance and it seemed to work. But I tested rapidly (this instance is expensive) and probably missed something.

**Comment by alrudak** [comment]
@guillaumekln Do plan to fix work 8 bit models for Ampere architecture this month ?

**Comment by guillaumekln** [comment]
Yes. I'm preparing a new major version with some breaking changes (see PR above). One of the change is to update the CUDA version in the Python wheels from 10.1 to 11.2. This should fix the compatibility issue.

**Comment by guillaumekln** [comment]
I think we are ready to release this version. However, this CUDA update will increase the size of the Python wheels we pushed on PyPI and we are now hitting the upload limit. We asked for a limit increase: https://github.com/pypa/pypi-support/issues/1057. It will most likely be accepted but I'm not sure about the response delay.

**Comment by guillaumekln** [comment]
I suspect this support request will not be processed anytime soon. So I went a different way and updated the library to dynamically load the cuBLAS library at runtime. This has the benefit of reducing the wheels size and allowing users to update the CUDA toolkit independently from the package (in the same CUDA major version).

I'm planning to release this new version by the end of the week.

**Comment by Andrewlesson** [comment]
I also have this problem. When I quantify it to int16, I do not report an error, but when I quantify it to int8, I will report the following errors.

![image](https://user-images.githubusercontent.com/10346684/172790072-bfd146b9-f893-49e6-9dc4-93c5289377a0.png)
